# Generated by the protocol buffer compiler.  DO NOT EDIT!
# source: cup_query.proto

import sys
_b=sys.version_info[0]<3 and (lambda x:x) or (lambda x:x.encode('latin1'))
from google.protobuf import descriptor as _descriptor
from google.protobuf import message as _message
from google.protobuf import reflection as _reflection
from google.protobuf import symbol_database as _symbol_database
from google.protobuf import descriptor_pb2
# @@protoc_insertion_point(imports)

_sym_db = _symbol_database.Default()




DESCRIPTOR = _descriptor.FileDescriptor(
  name='cup_query.proto',
  package='',
  syntax='proto3',
  serialized_pb=_b('\n\x0f\x63up_query.proto\"N\n\x0c\x43upCondition\x12\x11\n\tbakCardId\x18\x01 \x01(\t\x12\x0c\n\x04name\x18\x02 \x01(\t\x12\x0e\n\x06IDCard\x18\x03 \x01(\t\x12\r\n\x05phone\x18\x04 \x01(\t\"\x1b\n\tCupResult\x12\x0e\n\x06result\x18\x01 \x01(\t27\n\x0f\x43upQueryService\x12$\n\x05Query\x12\r.CupCondition\x1a\n.CupResult\"\x00\x42,\n\x1a\x63om.cardpay.datasource.cupB\x0c\x43upQueryImplP\x01\x62\x06proto3')
)
_sym_db.RegisterFileDescriptor(DESCRIPTOR)




_CUPCONDITION = _descriptor.Descriptor(
  name='CupCondition',
  full_name='CupCondition',
  filename=None,
  file=DESCRIPTOR,
  containing_type=None,
  fields=[
    _descriptor.FieldDescriptor(
      name='bakCardId', full_name='CupCondition.bakCardId', index=0,
      number=1, type=9, cpp_type=9, label=1,
      has_default_value=False, default_value=_b("").decode('utf-8'),
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      options=None),
    _descriptor.FieldDescriptor(
      name='name', full_name='CupCondition.name', index=1,
      number=2, type=9, cpp_type=9, label=1,
      has_default_value=False, default_value=_b("").decode('utf-8'),
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      options=None),
    _descriptor.FieldDescriptor(
      name='IDCard', full_name='CupCondition.IDCard', index=2,
      number=3, type=9, cpp_type=9, label=1,
      has_default_value=False, default_value=_b("").decode('utf-8'),
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      options=None),
    _descriptor.FieldDescriptor(
      name='phone', full_name='CupCondition.phone', index=3,
      number=4, type=9, cpp_type=9, label=1,
      has_default_value=False, default_value=_b("").decode('utf-8'),
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      options=None),
  ],
  extensions=[
  ],
  nested_types=[],
  enum_types=[
  ],
  options=None,
  is_extendable=False,
  syntax='proto3',
  extension_ranges=[],
  oneofs=[
  ],
  serialized_start=19,
  serialized_end=97,
)


_CUPRESULT = _descriptor.Descriptor(
  name='CupResult',
  full_name='CupResult',
  filename=None,
  file=DESCRIPTOR,
  containing_type=None,
  fields=[
    _descriptor.FieldDescriptor(
      name='result', full_name='CupResult.result', index=0,
      number=1, type=9, cpp_type=9, label=1,
      has_default_value=False, default_value=_b("").decode('utf-8'),
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      options=None),
  ],
  extensions=[
  ],
  nested_types=[],
  enum_types=[
  ],
  options=None,
  is_extendable=False,
  syntax='proto3',
  extension_ranges=[],
  oneofs=[
  ],
  serialized_start=99,
  serialized_end=126,
)

DESCRIPTOR.message_types_by_name['CupCondition'] = _CUPCONDITION
DESCRIPTOR.message_types_by_name['CupResult'] = _CUPRESULT

CupCondition = _reflection.GeneratedProtocolMessageType('CupCondition', (_message.Message,), dict(
  DESCRIPTOR = _CUPCONDITION,
  __module__ = 'cup_query_pb2'
  # @@protoc_insertion_point(class_scope:CupCondition)
  ))
_sym_db.RegisterMessage(CupCondition)

CupResult = _reflection.GeneratedProtocolMessageType('CupResult', (_message.Message,), dict(
  DESCRIPTOR = _CUPRESULT,
  __module__ = 'cup_query_pb2'
  # @@protoc_insertion_point(class_scope:CupResult)
  ))
_sym_db.RegisterMessage(CupResult)


DESCRIPTOR.has_options = True
DESCRIPTOR._options = _descriptor._ParseOptions(descriptor_pb2.FileOptions(), _b('\n\032com.cardpay.datasource.cupB\014CupQueryImplP\001'))
import grpc
from grpc.beta import implementations as beta_implementations
from grpc.beta import interfaces as beta_interfaces
from grpc.framework.common import cardinality
from grpc.framework.interfaces.face import utilities as face_utilities


class CupQueryServiceStub(object):

  def __init__(self, channel):
    """Constructor.

    Args:
      channel: A grpc.Channel.
    """
    self.Query = channel.unary_unary(
        '/CupQueryService/Query',
        request_serializer=CupCondition.SerializeToString,
        response_deserializer=CupResult.FromString,
        )


class CupQueryServiceServicer(object):

  def Query(self, request, context):
    context.set_code(grpc.StatusCode.UNIMPLEMENTED)
    context.set_details('Method not implemented!')
    raise NotImplementedError('Method not implemented!')


def add_CupQueryServiceServicer_to_server(servicer, server):
  rpc_method_handlers = {
      'Query': grpc.unary_unary_rpc_method_handler(
          servicer.Query,
          request_deserializer=CupCondition.FromString,
          response_serializer=CupResult.SerializeToString,
      ),
  }
  generic_handler = grpc.method_handlers_generic_handler(
      'CupQueryService', rpc_method_handlers)
  server.add_generic_rpc_handlers((generic_handler,))


class BetaCupQueryServiceServicer(object):
  """The Beta API is deprecated for 0.15.0 and later.

  It is recommended to use the GA API (classes and functions in this
  file not marked beta) for all further purposes. This class was generated
  only to ease transition from grpcio<0.15.0 to grpcio>=0.15.0."""
  def Query(self, request, context):
    context.code(beta_interfaces.StatusCode.UNIMPLEMENTED)


class BetaCupQueryServiceStub(object):
  """The Beta API is deprecated for 0.15.0 and later.

  It is recommended to use the GA API (classes and functions in this
  file not marked beta) for all further purposes. This class was generated
  only to ease transition from grpcio<0.15.0 to grpcio>=0.15.0."""
  def Query(self, request, timeout, metadata=None, with_call=False, protocol_options=None):
    raise NotImplementedError()
  Query.future = None


def beta_create_CupQueryService_server(servicer, pool=None, pool_size=None, default_timeout=None, maximum_timeout=None):
  """The Beta API is deprecated for 0.15.0 and later.

  It is recommended to use the GA API (classes and functions in this
  file not marked beta) for all further purposes. This function was
  generated only to ease transition from grpcio<0.15.0 to grpcio>=0.15.0"""
  request_deserializers = {
    ('CupQueryService', 'Query'): CupCondition.FromString,
  }
  response_serializers = {
    ('CupQueryService', 'Query'): CupResult.SerializeToString,
  }
  method_implementations = {
    ('CupQueryService', 'Query'): face_utilities.unary_unary_inline(servicer.Query),
  }
  server_options = beta_implementations.server_options(request_deserializers=request_deserializers, response_serializers=response_serializers, thread_pool=pool, thread_pool_size=pool_size, default_timeout=default_timeout, maximum_timeout=maximum_timeout)
  return beta_implementations.server(method_implementations, options=server_options)


def beta_create_CupQueryService_stub(channel, host=None, metadata_transformer=None, pool=None, pool_size=None):
  """The Beta API is deprecated for 0.15.0 and later.

  It is recommended to use the GA API (classes and functions in this
  file not marked beta) for all further purposes. This function was
  generated only to ease transition from grpcio<0.15.0 to grpcio>=0.15.0"""
  request_serializers = {
    ('CupQueryService', 'Query'): CupCondition.SerializeToString,
  }
  response_deserializers = {
    ('CupQueryService', 'Query'): CupResult.FromString,
  }
  cardinalities = {
    'Query': cardinality.Cardinality.UNARY_UNARY,
  }
  stub_options = beta_implementations.stub_options(host=host, metadata_transformer=metadata_transformer, request_serializers=request_serializers, response_deserializers=response_deserializers, thread_pool=pool, thread_pool_size=pool_size)
  return beta_implementations.dynamic_stub(channel, 'CupQueryService', cardinalities, options=stub_options)
# @@protoc_insertion_point(module_scope)
